/*
 ShareJS v0.2.0
 http://sharejs.org

 Copyright 2011 ShareJS Authors

 BSD licensed:
 https://github.com/josephg/ShareJS/raw/master/LICENSE
*/
function g(l){throw l;}var h=void 0,n=null;
(function(){function l(c,a){return function(){return c.apply(a,arguments)}}var y,u,v,r,C,F,w,o,x,p,G,H,I,D,E,z,k,J,A,B,K=Array.prototype.slice;p={};v=function(){function c(){}c.prototype.g=function(a,b){var c;this.e||(this.e={});(c=this.e)[a]||(c[a]=[]);this.e[a].push(b);return this};c.prototype.u=function(a,b){var c,d;this.e||(this.e={});d=(c=this.e)[a]||(c[a]=[]);for(c=0;c<d.length;)d[c]===b?d.splice(c,1):c++;return this};c.prototype.a=function(){var a,b,c,d,e;b=arguments[0];a=2<=arguments.length?
K.call(arguments,1):[];if(!((c=this.e)!=n&&c[b]))return this;e=this.e[b];c=0;for(d=e.length;c<d;c++)b=e[c],b.apply(this,a);return this};return c}();v.D=function(c){c=c.prototype||c;c.g=c.on=v.prototype.g;c.u=c.removeListener=v.prototype.u;c.a=v.prototype.a};if(typeof module!=="undefined"&&module!==n&&module.K)module.K=v;C=function(c,a,b,f){var d,e;d=function(b,c,f,d){a(f,b,c,"server");a(d,c,b,"client")};c.S=c.transformX=e=function(a,c){var j,s,k,l,q,o,t,p,r;b(a);b(c);k=[];o=0;for(p=c.length;o<p;o++){s=
c[o];l=[];for(j=0;j<a.length;)if(q=[],d(a[j],s,l,q),j++,q.length===1)s=q[0];else{if(q.length===0){t=a.slice(j);s=0;for(q=t.length;s<q;s++)j=t[s],f(l,j)}else{s=e(a.slice(j),q);q=s[0];s=s[1];t=0;for(r=q.length;t<r;t++)j=q[t],f(l,j);q=0;for(t=s.length;q<t;q++)j=s[q],f(k,j)}s=n;break}s!=n&&f(k,s);a=l}return[a,k]};c.transform=c.transform=function(b,c,f){f==="server"||f==="client"||g(Error("type must be 'server' or 'client'"));if(c.length===0)return b;if(b.length===1&&c.length===1)return a([],b[0],c[0],
f);f==="server"?(b=e(b,c),b=b[0]):(b=e(c,b),b=b[1]);return b}};k={name:"text"};k.initialVersion=k.B=function(){return""};z=function(c,a,b){return c.slice(0,a)+b+c.slice(a)};F=function(c){typeof c.p!=="number"&&g(Error("component missing position field"));typeof c.i==="string"^typeof c.d==="string"||g(Error("component needs an i or d field"));c.p>=0||g(Error("position cannot be negative"))};w=function(c){var a,b,f;b=0;for(f=c.length;b<f;b++)a=c[b],F(a);return!0};k.apply=function(c,a){var b,f,d,e;w(a);
d=0;for(e=a.length;d<e;d++)b=a[d],b.i!=n?c=z(c,b.p,b.i):(f=c.slice(b.p,b.p+b.d.length),b.d!==f&&g(Error("Delete component '"+b.d+"' does not match deleted text '"+f+"'")),c=c.slice(0,b.p)+c.slice(b.p+b.d.length));return c};k.T=r=function(c,a){var b,f,d;if(!(a.i===""||a.d===""))return c.length===0?c.push(a):(b=c[c.length-1],b.i!=n&&a.i!=n&&b.p<=(f=a.p)&&f<=b.p+b.i.length?c[c.length-1]={i:z(b.i,a.p-b.p,a.i),p:b.p}:b.d!=n&&a.d!=n&&a.p<=(d=b.p)&&d<=a.p+a.d.length?c[c.length-1]={d:z(a.d,b.p-a.p,b.d),p:a.p}:
c.push(a))};k.compose=k.k=function(c,a){var b,f,d,e;w(c);w(a);f=c.slice();d=0;for(e=a.length;d<e;d++)b=a[d],r(f,b);return f};k.compress=k.V=function(c){return k.k([],c)};k.normalize=function(c){var a,b,f,d;b=[];if(c.i!=n||c.p!=n)c=[c];f=0;for(d=c.length;f<d;f++)a=c[f],a.p==n&&(a.p=0),r(b,a);return b};A=function(c,a,b){return a.i!=n?a.p<c||a.p===c&&b?c+a.i.length:c:c<=a.p?c:c<=a.p+a.d.length?a.p:c-a.d.length};k.transformCursor=function(c,a,b){var f,d,e;d=0;for(e=a.length;d<e;d++)f=a[d],c=A(c,f,b);
return c};k.H=J=function(c,a,b,f){var d,e;w([a]);w([b]);if(a.i!=n)r(c,{i:a.i,p:A(a.p,b,f==="server")});else if(b.i!=n)f=a.d,a.p<b.p&&(r(c,{d:f.slice(0,b.p-a.p),p:a.p}),f=f.slice(b.p-a.p)),f!==""&&r(c,{d:f,p:a.p+b.i.length});else if(a.p>=b.p+b.d.length)r(c,{d:a.d,p:a.p-b.d.length});else if(a.p+a.d.length<=b.p)r(c,a);else if(f={d:"",p:a.p},a.p<b.p&&(f.d=a.d.slice(0,b.p-a.p)),a.p+a.d.length>b.p+b.d.length&&(f.d+=a.d.slice(b.p+b.d.length-a.p)),e=Math.max(a.p,b.p),d=Math.min(a.p+a.d.length,b.p+b.d.length),
a=a.d.slice(e-a.p,d-a.p),d=b.d.slice(e-b.p,d-b.p),a!==d&&g(Error("Delete ops delete different text in the same region of the document")),f.d!=="")f.p=A(f.p,b),r(c,f);return c};H=function(c){return c.i!=n?{d:c.i,p:c.p}:{i:c.d,p:c.p}};k.L=k.invert=function(c){var a,b,f,d;f=c.slice().reverse();d=[];a=0;for(b=f.length;a<b;a++)c=f[a],d.push(H(c));return d};p.types||(p.types={});C(k,J,w,r);p.types.text=k;typeof json!=="undefined"&&json!==n||(json={});json.name="json";json.B=function(){return n};json.M=
function(c){var a;a={p:c.p};c.si!==h&&(a.sd=c.si);c.sd!==h&&(a.si=c.sd);c.oi!==h&&(a.od=c.oi);c.od!==h&&(a.oi=c.od);c.li!==h&&(a.ld=c.li);c.ld!==h&&(a.li=c.ld);c.na!==h&&(a.na=-c.na);if(c.lm!==h)a.lm=c.p[c.p.length-1],a.p=c.p.slice(0,c.p.length-1).concat([c.lm]);return a};json.L=function(c){var a,b,f,d;f=c.slice().reverse();d=[];a=0;for(b=f.length;a<b;a++)c=f[a],d.push(json.M(c));return d};json.I=function(){};D=function(c){return Object.prototype.toString.call(c)==="[object Array]"};json.j=function(c){D(c)||
g(Error("Referenced element not a list"))};json.w=function(c){c.constructor!==Object&&g(Error("Referenced element not an object (it was "+JSON.stringify(c)+")"))};json.apply=function(c,a){var b,f,d,e,m,i,j,k,l,p,q,r,t,a=o(a);f={data:o(c)};try{m=0;for(q=a.length;m<q;m++){b=a[m];l=k=n;e=f;i="data";t=b.p;p=0;for(r=t.length;p<r;p++)j=t[p],k=e,l=i,e=e[i],i=j,k==n&&g(Error("Path invalid"));b.na!==h?(typeof e[i]!=="number"&&g(Error("Referenced element not a number")),e[i]+=b.na):b.si!==h?(typeof e!=="string"&&
g(Error("Referenced element not a string (it was "+JSON.stringify(e)+")")),k[l]=e.slice(0,i)+b.si+e.slice(i)):b.sd!==h?(typeof e!=="string"&&g(Error("Referenced element not a string")),e.slice(i,i+b.sd.length)!==b.sd&&g(Error("Deleted string does not match")),k[l]=e.slice(0,i)+e.slice(i+b.sd.length)):b.li!==h&&b.ld!==h?(json.j(e),e[i]=b.li):b.li!==h?(json.j(e),e.splice(i,0,b.li)):b.ld!==h?(json.j(e),e.splice(i,1)):b.lm!==h?(json.j(e),b.lm!==i&&(d=e[i],e.splice(i,1),e.splice(b.lm,0,d))):b.oi!==h?(json.w(e),
e[i]=b.oi):b.od!==h&&(json.w(e),delete e[i])}}catch(u){g(u)}return f.data};json.P=function(c,a){var b,f,d;if(c.length!==a.length)return!1;b=0;for(d=c.length;b<d;b++)if(f=c[b],f!==a[b])return!1;return!0};json.append=function(c,a){var b,a=o(a);return c.length!==0&&json.P(a.p,(b=c[c.length-1]).p)?b.na!==h&&a.na!==h?c[c.length-1]={p:b.p,na:b.na+a.na}:b.li!==h&&a.li===h&&a.ld===b.li?b.ld!==h?delete b.li:c.pop():b.od!==h&&b.oi===h&&a.oi!==h&&a.od===h?b.oi=a.oi:a.lm!==h&&a.p[a.p.length-1]===a.lm?n:c.push(a):
c.push(a)};json.k=function(c,a){var b,f,d,e;f=o(c);d=0;for(e=a.length;d<e;d++)b=a[d],json.append(f,b);return f};json.normalize=function(c){var a,b,f,d;b=[];D(c)||(c=[c]);f=0;for(d=c.length;f<d;f++)a=c[f],a.p==n&&(a.p=[]),json.append(b,a);return b};o=function(c){return JSON.parse(JSON.stringify(c))};json.z=function(c,a){var b,c=c.slice(),a=a.slice();c.unshift("data");a.unshift("data");c=c.slice(0,c.length-1);a=a.slice(0,a.length-1);if(a.length===0)return-1;for(b=0;c[b]===a[b]&&b<c.length;)if(b++,b===
a.length)return b-1};json.R=function(c,a,b,f){var d,e,m,i,j,a=o(a);a.na!==h&&a.p.push(0);b.na!==h&&b.p.push(0);d=json.z(a.p,b.p);e=json.z(b.p,a.p);m=a.p.length;i=b.p.length;a.na!==h&&a.p.pop();b.na!==h&&b.p.pop();if(b.na){if(e!=n&&i>=m&&b.p[e]===a.p[e])if(a.ld!==h)e=o(b),e.p=e.p.slice(m),a.ld=json.apply(o(a.ld),[e]);else if(a.od!==h)e=o(b),e.p=e.p.slice(m),a.od=json.apply(o(a.od),[e]);json.append(c,a);return c}if(e!=n&&i>m&&a.p[e]===b.p[e])if(a.ld!==h)e=o(b),e.p=e.p.slice(m),a.ld=json.apply(o(a.ld),
[e]);else if(a.od!==h)e=o(b),e.p=e.p.slice(m),a.od=json.apply(o(a.od),[e]);if(d!=n&&(e=m===i,b.na===h))if(b.si!==h||b.sd!==h){if(a.si!==h||a.sd!==h){e||g(Error("must be a string?"));m=a.p[m-1];e=b.p[i-1];i={p:m};m={p:e};a.si!=n&&(i.i=a.si);a.sd!=n&&(i.d=a.sd);b.si!=n&&(m.i=b.si);b.sd!=n&&(m.d=b.sd);b=[];k.H(b,i,m,f);m=0;for(e=b.length;m<e;m++)i=b[m],f={p:a.p.slice(0,d)},f.p.push(i.p),i.i!=n&&(f.si=i.i),i.d!=n&&(f.sd=i.d),json.append(c,f);return c}}else if(b.li!==h&&b.ld!==h){if(b.p[d]===a.p[d])if(e){if(a.ld!==
h)if(a.li!==h&&f==="client")a.ld=o(b.li);else return c}else return c}else if(b.li!==h)a.li!==h&&a.ld===h&&e&&a.p[d]===b.p[d]?f==="server"&&a.p[d]++:b.p[d]<=a.p[d]&&a.p[d]++,a.lm!==h&&e&&b.p[d]<=a.lm&&a.lm++;else if(b.ld!==h){if(a.lm!==h&&e){if(b.p[d]===a.p[d])return c;f=b.p[d];e=a.p[d];j=a.lm;(f<j||f===j&&e<j)&&a.lm--}if(b.p[d]<a.p[d])a.p[d]--;else if(b.p[d]===a.p[d])if(i<m)return c;else if(a.ld!==h)if(a.li!==h)delete a.ld;else return c}else if(b.lm!==h)if(a.lm!==h&&m===i){if(e=a.p[d],j=a.lm,i=b.p[d],
b=b.lm,i!==b)if(e===i)if(f==="client")a.p[d]=b,e===j&&(a.lm=b);else return c;else e>i&&a.p[d]--,e>b?a.p[d]++:e===b&&i>b&&(a.p[d]++,e===j&&a.lm++),j>i?a.lm--:j===i&&j>e&&a.lm--,j>b?a.lm++:j===b&&(b>i&&j>e||b<i&&j<e?f==="server"&&a.lm++:j>e?a.lm++:j===i&&a.lm--)}else a.li!==h&&a.ld===h&&e?(e=b.p[d],j=b.lm,f=a.p[d],f>e&&a.p[d]--,f>j&&a.p[d]++):(e=b.p[d],j=b.lm,f=a.p[d],f===e?a.p[d]=j:(f>e&&a.p[d]--,f>j?a.p[d]++:f===j&&e>j&&a.p[d]++));else if(b.oi!==h&&b.od!==h){if(a.p[d]===b.p[d])if(a.oi!==h&&e)if(f===
"server")return c;else a.od=b.oi;else return c}else if(b.oi!==h){if(a.oi!==h&&a.p[d]===b.p[d])if(f==="client")json.append(c,{p:a.p,od:b.oi});else return c}else if(b.od!==h&&a.p[d]===b.p[d]){if(!e)return c;if(a.oi!==h)delete a.od;else return c}json.append(c,a);return c};p.types||(p.types={});C(json,json.R,json.I,json.append);p.types.json=json;B||(B=p.types);window.io||g(Error("Must load socket.io before this library"));I=window.io;u=function(){function c(a,b,c,d,e){this.A=a;this.name=b;this.version=
c;this.type=d;this.s=l(this.s,this);this.l=l(this.l,this);this.type.k==n&&g(Error("Handling types without compose() defined is not currently implemented"));this.snapshot=e;this.b=n;this.o=[];this.c=n;this.t=[];this.F={};this.W=[]}c.prototype.l=function(){if(this.b===n&&this.c!==n)return this.b=this.c,this.o=this.t,this.c=n,this.t=[],this.A.send({doc:this.name,op:this.b,v:this.version},l(function(a){var b,c,d,e;if(a.v===n){e=this.o;c=0;for(d=e.length;c<d;c++)b=e[c],b(n);this.b=n;g(Error(a.error))}a.v!==
this.version&&g(Error("Invalid version from server"));this.F[this.version]=this.b;this.version++;d=this.o;a=0;for(c=d.length;a<c;a++)b=d[a],b(this.b,n);this.b=n;return this.l()},this))};c.prototype.s=function(a){var b,c;if(!(a.v<this.version)){a.doc!==this.name&&g(Error("Expected docName "+this.name+" but got "+a.doc));a.v!==this.version&&g(Error("Expected version "+this.version+" but got "+a.v));a=a.op;this.F[this.version]=a;b=this.type.S||l(function(a,b){var c,f;f=this.type.transform(a,b,"server");
c=this.type.transform(b,a,"client");return[f,c]},this);if(this.b!==n)c=b(a,this.b),a=c[0],this.b=c[1];if(this.c!==n)b=b(a,this.c),a=b[0],this.c=b[1];this.snapshot=this.type.apply(this.snapshot,a);this.version++;this.a("remoteop",a);return this.a("change",a)}};c.prototype.Q=function(a,b,c){var d;if(b==n)b=this.version;if(typeof b==="function")c=b,b=this.version;if(((d=this.type)!=n?d.normalize:h)!=n)a=this.type.normalize(a);for(;b<this.version;)(d=this.X[b])||g(Error("Op version too old")),a=this.type.transform(a,
d,"client"),b++;this.snapshot=this.type.apply(this.snapshot,a);this.c=this.c!==n?this.type.k(this.c,a):a;c&&this.t.push(c);this.a("change",a);return setTimeout(this.l,0)};c.prototype.close=function(a){return this.A.send({doc:this.name,open:!1},l(function(){a&&a();this.a("closed")},this))};return c}();v.D(u);u.prototype.submitOp=u.prototype.Q;u.prototype.close=u.prototype.close;y=function(){function c(a,b,c){this.r=l(this.r,this);this.m=l(this.m,this);this.n=l(this.n,this);this.h=new I.Socket(a,{port:b,
Y:c?path+"/socket.io":"socket.io"});this.h.on("connect",this.m);this.h.on("disconnect",this.n);this.h.on("message",this.r);this.h.connect();this.f={};this.q=0}c.prototype.n=function(){return this.a("disconnect")};c.prototype.m=function(){return this.a("connect")};c.prototype.send=function(a,b){var c,d;c=a.doc;c===this.O?delete a.doc:this.O=c;this.h.send(a);if(b)return d=l(function(a){var d;d=l(function(i){if(i.doc===c)return this.u(a,d),b(i)},this);return this.g(a,d)},this),d(a.open===!0?"open":a.open===
!1?"close":a.create?"create":a.snapshot===n?"snapshot":a.op?"op response":h)};c.prototype.r=function(a){var b,c;b=a.doc;b!==h?this.N=b:a.doc=b=this.N;this.a("message",a);c=a.open===!0||a.open===!1&&a.error?"open":a.open===!1?"close":a.snapshot!==h?"snapshot":a.create?"create":a.op?"op":a.v!==h?"op response":h;this.a(c,a);if(c==="op"&&(b=this.f[b]))return b.s(a)};c.prototype.C=function(a){var b,c;c=a.doc;this.f[c]&&g(Error("Document "+c+" already followed"));b=a.type;typeof b==="string"&&(b=B[b]);
b=new u(this,c,a.v,b,a.snapshot);b.created=!!a.create;this.f[c]=b;this.q++;b.g("closed",l(function(){delete this.f[c];return this.q--},this));return b};c.prototype.openExisting=function(a,b){if(this.f[a]!=n)return this.f[a];return this.send({doc:a,open:!0,snapshot:n},l(function(a){return a.error?b(n,Error(a.error)):b(this.C(a))},this))};c.prototype.open=function(a,b,c){typeof b==="function"&&(c=b,b="text");c||(c=function(){});typeof b==="string"&&(b=B[b]);if(a!=n&&this.f[a]!=n)a=this.f[a],a.type===
b?c(a):c(a,"Type mismatch");else return this.send({doc:a,open:!0,create:!0,snapshot:n,type:b.name},l(function(a){return a.error?c(n,a.error):(a.snapshot===h&&(a.snapshot=b.B()),a.type=b,c(this.C(a)))},this))};c.prototype.create=function(a,b){return E(n,a,b)};c.prototype.disconnect=function(){if(this.G!=n)return this.a("disconnected"),this.G.J(),this.G=n};return c}();v.D(y);x={};G=function(c,a,b){var f;if(c==n)c=window.location.hostname;if(a==n)a=window.location.port;f=c;a!=n&&(f+=":"+a);x[f]||(c=
new y(c,a,b),c.g("disconnected",function(){return delete x[f]}),x[f]=c);return x[f]};E=function(c,a,b,f){var d;typeof b==="function"&&(f=b,b=n);b==n&&(b={});d=G(b.host,b.port,b.U);return d.open(c,a,function(a,b){return a===n?f(n,b):(a.g("closed",function(){return setTimeout(function(){if(d.q===0)return d.J()},0)}),f(a))})};p.Connection=y;p.Document=u;p.open=E;window.sharejs=p}).call(this);