/*
 ShareJS v0.3.0
 http://sharejs.org

 Copyright 2011 ShareJS Authors

 BSD licensed:
 https://github.com/josephg/ShareJS/raw/master/LICENSE
*/
function f(k){throw k;}var o=void 0,r=null;
(function(){function k(b,a){return function(){return b.apply(a,arguments)}}var u,w,m,l,B,F,s,t,j,G,H,C,D,x,y,g,E,z,v,I=Array.prototype.slice;j={version:"0.3.0"};D=typeof!0!=="undefined"?function(b){return setTimeout(b,0)}:D=process.nextTick;m=function(){function b(){}b.prototype.f=function(a,c){var b;this.b||(this.b={});(b=this.b)[a]||(b[a]=[]);this.b[a].push(c);return this};b.prototype.m=function(a,c){var b,e;this.b||(this.b={});e=(b=this.b)[a]||(b[a]=[]);for(b=0;b<e.length;)e[b]===c&&(e[b]=o),b++;
D(k(function(){var c;return this.b[a]=function(){var b,d,e,h;e=this.b[a];h=[];for(b=0,d=e.length;b<d;b++)(c=e[b])&&h.push(c);return h}.call(this)},this));return this};b.prototype.a=function(){var a,c,b,e,i;c=arguments[0];a=2<=arguments.length?I.call(arguments,1):[];if(!((b=this.b)!=r&&b[c]))return this;i=this.b[c];for(b=0,e=i.length;b<e;b++)(c=i[b])&&c.apply(this,a);return this};return b}();m.r=function(b){b=b.prototype||b;b.f=b.on=m.prototype.f;b.m=b.removeListener=m.prototype.m;b.a=b.emit=m.prototype.a};
if(typeof module!=="undefined"&&module!==r&&module.o)module.o=m;j._bt=B=function(b,a,c,d){var e,i;e=function(b,c,d,e){a(d,b,c,"left");a(e,c,b,"right")};b.L=b.transformX=i=function(a,b){var n,h,g,k,p,A,q,j,l,m;c(a);c(b);k=[];for(A=0,j=b.length;A<j;A++){h=b[A];g=[];for(n=0;n<a.length;)if(p=[],e(a[n],h,g,p),n++,p.length===1)h=p[0];else{if(p.length===0){q=a.slice(n);for(p=0,h=q.length;p<h;p++)n=q[p],d(g,n)}else{m=i(a.slice(n),p);h=m[0];p=m[1];for(q=0,l=h.length;q<l;q++)n=h[q],d(g,n);for(h=0,q=p.length;h<
q;h++)n=p[h],d(k,n)}h=r;break}h!=r&&d(k,h);a=g}return[a,k]};return b.transform=b.transform=function(b,c,d){var e,g;d==="left"||d==="right"||f(Error("type must be 'left' or 'right'"));if(c.length===0)return b;return b.length===1&&c.length===1?a([],b[0],c[0],d):d==="left"?(g=i(b,c),e=g[0],e):(e=i(c,b),g=e[1],g)}};if(typeof!0==="undefined")j.u=B;g={name:"text"};g.create=g.create=function(){return""};y=function(b,a,c){return b.slice(0,a)+c+b.slice(a)};F=function(b){typeof b.p!=="number"&&f(Error("component missing position field"));
typeof b.i==="string"^typeof b.d==="string"||f(Error("component needs an i or d field"));b.p>=0||f(Error("position cannot be negative"))};s=function(b){var a,c,d;for(c=0,d=b.length;c<d;c++)a=b[c],F(a);return!0};g.apply=function(b,a){var c,d,e,i;s(a);for(e=0,i=a.length;e<i;e++)c=a[e],c.i!=r?b=y(b,c.p,c.i):(d=b.slice(c.p,c.p+c.d.length),c.d!==d&&f(Error("Delete component '"+c.d+"' does not match deleted text '"+d+"'")),b=b.slice(0,c.p)+b.slice(c.p+c.d.length));return b};g.C=l=function(b,a){var c,d,
e;if(!(a.i===""||a.d===""))return b.length===0?b.push(a):(c=b[b.length-1],c.i!=r&&a.i!=r&&c.p<=(d=a.p)&&d<=c.p+c.i.length?b[b.length-1]={i:y(c.i,a.p-c.p,a.i),p:c.p}:c.d!=r&&a.d!=r&&a.p<=(e=c.p)&&e<=a.p+a.d.length?b[b.length-1]={d:y(a.d,c.p-a.p,c.d),p:a.p}:b.push(a))};g.compose=g.w=function(b,a){var c,d,e,i;s(b);s(a);d=b.slice();for(e=0,i=a.length;e<i;e++)c=a[e],l(d,c);return d};g.compress=g.F=function(b){return g.w([],b)};g.normalize=function(b){var a,c,d,e;c=[];if(b.i!=r||b.p!=r)b=[b];for(d=0,e=
b.length;d<e;d++)a=b[d],a.p==r&&(a.p=0),l(c,a);return c};z=function(b,a,c){return a.i!=r?a.p<b||a.p===b&&c?b+a.i.length:b:b<=a.p?b:b<=a.p+a.d.length?a.p:b-a.d.length};g.transformCursor=function(b,a,c){var d,e,i;for(e=0,i=a.length;e<i;e++)d=a[e],b=z(b,d,c);return b};g._tc=E=function(b,a,c,d){var e,i;s([a]);s([c]);if(a.i!=r)l(b,{i:a.i,p:z(a.p,c,d==="right")});else if(c.i!=r)d=a.d,a.p<c.p&&(l(b,{d:d.slice(0,c.p-a.p),p:a.p}),d=d.slice(c.p-a.p)),d!==""&&l(b,{d:d,p:a.p+c.i.length});else if(a.p>=c.p+c.d.length)l(b,
{d:a.d,p:a.p-c.d.length});else if(a.p+a.d.length<=c.p)l(b,a);else if(d={d:"",p:a.p},a.p<c.p&&(d.d=a.d.slice(0,c.p-a.p)),a.p+a.d.length>c.p+c.d.length&&(d.d+=a.d.slice(c.p+c.d.length-a.p)),i=Math.max(a.p,c.p),e=Math.min(a.p+a.d.length,c.p+c.d.length),a=a.d.slice(i-a.p,e-a.p),e=c.d.slice(i-c.p,e-c.p),a!==e&&f(Error("Delete ops delete different text in the same region of the document")),d.d!=="")d.p=z(d.p,c),l(b,d);return b};H=function(b){return b.i!=r?{d:b.i,p:b.p}:{i:b.d,p:b.p}};g.H=g.invert=function(b){var a,
c,d,e;d=b.slice().reverse();e=[];for(a=0,c=d.length;a<c;a++)b=d[a],e.push(H(b));return e};typeof!0!=="undefined"?(j.types||(j.types={}),B(g,E,s,l),j.types.text=g):(module.o=g,require("./helpers").u(g,E,s,l));typeof!0==="undefined"&&(g=require("./text"));g.api={provides:{text:!0},getLength:function(){return this.g.length},getText:function(){return this.g},insert:function(b,a,c){a==r&&(a=0);b=[{p:a,i:b}];this.s(b,c);return b},del:function(b,a,c){b=[{p:a,d:this.g.slice(a,a+b)}];this.s(b,c);return b},
_register:function(){return this.f("remoteop",function(b){var a,c,d,e;e=[];for(c=0,d=b.length;c<d;c++)a=b[c],e.push(a.i!==o?this.a("insert",a.i,a.p):this.a("delete",a.d,a.p));return e})}};typeof!0!=="undefined"?(v||(v=j.types),window.io||f(Error("Must load socket.io before this library")),C=window.io):(v=require("../types"),C=require("../../thirdparty/Socket.io-node-client").I,m=require("./microevent"));w=function(b,a,c,d,e){var i,g,j,n,h,l,m;this.name=a;this.version=c;this.type=d;this.type.compose==
r&&f(Error("Handling types without compose() defined is not currently implemented"));this.n=function(a){this.snapshot=this.g=a};this.n(e);g=r;i=[];h=r;n=[];l={};m=k(function(){if(g===r&&h!==r)return g=h,i=n,h=r,n=[],b.send({doc:this.name,op:g,v:this.version},k(function(a){var b,c,d;if(a.v===r){for(c=0,d=i.length;c<d;c++)b=i[c],b(r);g=r;f(Error(a.error))}a.v!==this.version&&f(Error("Invalid version from server"));l[this.version]=g;this.version++;for(a=0,c=i.length;a<c;a++)b=i[a],b(g,r);g=r;return m()},
this))},this);this.t=function(a){var b,c,d;if(!(a.v<this.version))return a.doc!==this.name&&f(Error("Expected docName "+this.name+" but got "+a.doc)),a.v!==this.version&&f(Error("Expected version "+this.version+" but got "+a.v)),a=a.op,l[this.version]=a,c=this.type.transformX||k(function(a,b){var c,d;c=this.type.transform(a,b,"left");d=this.type.transform(b,a,"right");return[c,d]},this),g!==r&&(b=c(g,a),g=b[0],a=b[1]),h!==r&&(d=c(h,a),h=d[0],a=d[1]),b=this.g,this.n(this.type.apply(b,a)),this.version++,
this.a("remoteop",a,b),this.a("change",a,b)};this.submitOp=this.s=function(a,b,c){var d;if(b==r)b=this.version;if(typeof b==="function")c=b,b=this.version;for(this.type.normalize!=r&&(a=this.type.normalize(a));b<this.version;)(d=l[b])||f(Error("Op version too old")),a=this.type.transform(a,d,"left"),b++;this.n(this.type.apply(this.g,a));h=h!==r?this.type.compose(h,a):a;c&&n.push(c);this.a("change",a);return setTimeout(m,0)};this.close=this.close=function(a){return b.send({doc:this.name,open:!1},k(function(){a&&
a();this.a("closed")},this))};if(this.type.api){c=this.type.api;for(j in c)a=c[j],this[j]=a;typeof this._register==="function"&&this._register()}else this.J=this.provides={};return this};m.r(w);u=function(){function b(a,b,d){this.l=k(this.l,this);this.j=k(this.j,this);this.k=k(this.k,this);this.e=new C.Socket(a,{port:b,K:d?path+"/socket.io":"socket.io"});this.e.on("connect",this.j);this.e.on("disconnect",this.k);this.e.on("message",this.l);this.e.connect();this.c={};this.h=0}b.prototype.k=function(){return this.a("disconnect")};
b.prototype.j=function(){return this.a("connect")};b.prototype.send=function(a,b){var d,e,g;d=a.doc;d===this.A?delete a.doc:this.A=d;this.e.send(a);if(b)return e=k(function(a){var e;e=k(function(g){if(g.doc===d)return this.m(a,e),b(g)},this);return this.f(a,e)},this),g=a.open===!0?"open":a.open===!1?"close":a.create?"create":a.snapshot===r?"snapshot":a.op?"op response":o,e(g)};b.prototype.l=function(a){var b,d;b=a.doc;b!==o?this.z=b:a.doc=b=this.z;this.a("message",a);d=a.open===!0||a.open===!1&&a.error?
"open":a.open===!1?"close":a.snapshot!==o?"snapshot":a.create?"create":a.op?"op":a.v!==o?"op response":o;this.a(d,a);if(d==="op"&&(b=this.c[b]))return b.t(a)};b.prototype.q=function(a){var b,d;d=a.doc;this.c[d]&&f(Error("Doc "+d+" already open"));b=a.type;typeof b==="string"&&(b=v[b]);b=new w(this,d,a.v,b,a.snapshot);b.created=!!a.create;this.c[d]=b;this.h++;b.f("closed",k(function(){delete this.c[d];return this.h--},this));return b};b.prototype.openExisting=function(a,b){return this.c[a]!=r?this.c[a]:
this.send({doc:a,open:!0,snapshot:r},k(function(a){return a.error?b(r,Error(a.error)):b(this.q(a))},this))};b.prototype.open=function(a,b,d){typeof b==="function"&&(d=b,b="text");d||(d=function(){});typeof b==="string"&&(b=v[b]);if(a!=r&&this.c[a]!=r)a=this.c[a],a.type===b?d(a):d(a,"Type mismatch");else return this.send({doc:a,open:!0,create:!0,snapshot:r,type:b.name},k(function(a){return a.error?d(r,a.error):(a.snapshot===o&&(a.snapshot=b.create()),a.type=b,d(this.q(a)))},this))};b.prototype.create=
function(a,b){return x(r,a,b)};b.prototype.disconnect=function(){if(this.e)return this.a("disconnected"),this.e.disconnect(),this.e=r};return b}();m.r(u);t={};G=function(b,a,c){var d;if(typeof!0!=="undefined"){if(b==r)b=window.location.hostname;if(a==r)a=window.location.port}d=b;a!=r&&(d+=":"+a);t[d]||(b=new u(b,a,c),b.f("disconnected",function(){return delete t[d]}),t[d]=b);return t[d]};x=function(b,a,c,d){var e;typeof c==="function"&&(d=c,c=r);c==r&&(c={});e=G(c.host,c.port,c.D);return e.open(b,
a,function(a,b){return a===r?(e.h===0&&e.disconnect(),d(r,b)):(a.f("closed",function(){return setTimeout(function(){if(e.h===0)return e.disconnect()},0)}),d(a))})};j.G=function(){return console.log(t)};typeof!0!=="undefined"?(j.Connection=u,j.Doc=w,j.open=x,window.sharejs=j):(j.B=u,j.open=x)}).call(this);