(function(){
/*
 ShareJS v0.3.0
 http://sharejs.org

 Copyright 2011 ShareJS Authors

 BSD licensed:
 https://github.com/josephg/ShareJS/raw/master/LICENSE
*/
function g(j){throw j;}var n=void 0,q=null;
(function(){function j(b,a){return function(){return b.apply(a,arguments)}}var u,w,o,k,B,F,s,t,l,G,H,C,D,x,y,f,E,z,v,J=Array.prototype.slice;l={version:"0.3.0"};D=typeof!0!=="undefined"?function(b){return setTimeout(b,0)}:D=process.nextTick;o=function(){function b(){}b.prototype.f=function(a,c){var b;this.c||(this.c={});(b=this.c)[a]||(b[a]=[]);this.c[a].push(c);return this};b.prototype.r=function(a,c){var b,e;this.c||(this.c={});e=(b=this.c)[a]||(b[a]=[]);for(b=0;b<e.length;)e[b]===c&&(e[b]=n),b++;
D(j(function(){var c;return this.c[a]=function(){var b,d,e,i;e=this.c[a];i=[];for(b=0,d=e.length;b<d;b++)(c=e[b])&&i.push(c);return i}.call(this)},this));return this};b.prototype.a=function(){var a,b,d,e,h;b=arguments[0];a=2<=arguments.length?J.call(arguments,1):[];if(!((d=this.c)!=q&&d[b]))return this;h=this.c[b];for(d=0,e=h.length;d<e;d++)(b=h[d])&&b.apply(this,a);return this};return b}();o.q=function(b){b=b.prototype||b;b.f=b.on=o.prototype.f;b.r=b.removeListener=o.prototype.r;b.a=b.emit=o.prototype.a};
if(typeof module!=="undefined"&&module!==q&&module.n)module.n=o;l._bt=B=function(b,a,c,d){var e,h;e=function(b,c,d,e){a(d,b,c,"left");a(e,c,b,"right")};b.H=b.transformX=h=function(a,b){var m,i,f,j,p,A,r,I,l,k;c(a);c(b);j=[];for(A=0,I=b.length;A<I;A++){i=b[A];f=[];for(m=0;m<a.length;)if(p=[],e(a[m],i,f,p),m++,p.length===1)i=p[0];else{if(p.length===0){r=a.slice(m);for(p=0,i=r.length;p<i;p++)m=r[p],d(f,m)}else{k=h(a.slice(m),p);i=k[0];p=k[1];for(r=0,l=i.length;r<l;r++)m=i[r],d(f,m);for(i=0,r=p.length;i<
r;i++)m=p[i],d(j,m)}i=q;break}i!=q&&d(j,i);a=f}return[a,j]};return b.transform=b.transform=function(b,c,d){var e,f;d==="left"||d==="right"||g(Error("type must be 'left' or 'right'"));if(c.length===0)return b;return b.length===1&&c.length===1?a([],b[0],c[0],d):d==="left"?(f=h(b,c),e=f[0],e):(e=h(c,b),f=e[1],f)}};if(typeof!0==="undefined")l.u=B;f={name:"text"};f.create=f.create=function(){return""};y=function(b,a,c){return b.slice(0,a)+c+b.slice(a)};F=function(b){typeof b.p!=="number"&&g(Error("component missing position field"));
typeof b.i==="string"^typeof b.d==="string"||g(Error("component needs an i or d field"));b.p>=0||g(Error("position cannot be negative"))};s=function(b){var a,c,d;for(c=0,d=b.length;c<d;c++)a=b[c],F(a);return!0};f.apply=function(b,a){var c,d,e,h;s(a);for(e=0,h=a.length;e<h;e++)c=a[e],c.i!=q?b=y(b,c.p,c.i):(d=b.slice(c.p,c.p+c.d.length),c.d!==d&&g(Error("Delete component '"+c.d+"' does not match deleted text '"+d+"'")),b=b.slice(0,c.p)+b.slice(c.p+c.d.length));return b};f.C=k=function(b,a){var c,d,
e;if(!(a.i===""||a.d===""))return b.length===0?b.push(a):(c=b[b.length-1],c.i!=q&&a.i!=q&&c.p<=(d=a.p)&&d<=c.p+c.i.length?b[b.length-1]={i:y(c.i,a.p-c.p,a.i),p:c.p}:c.d!=q&&a.d!=q&&a.p<=(e=c.p)&&e<=a.p+a.d.length?b[b.length-1]={d:y(a.d,c.p-a.p,c.d),p:a.p}:b.push(a))};f.compose=f.w=function(b,a){var c,d,e,h;s(b);s(a);d=b.slice();for(e=0,h=a.length;e<h;e++)c=a[e],k(d,c);return d};f.compress=f.D=function(b){return f.w([],b)};f.normalize=function(b){var a,c,d,e;c=[];if(b.i!=q||b.p!=q)b=[b];for(d=0,e=
b.length;d<e;d++)a=b[d],a.p==q&&(a.p=0),k(c,a);return c};z=function(b,a,c){return a.i!=q?a.p<b||a.p===b&&c?b+a.i.length:b:b<=a.p?b:b<=a.p+a.d.length?a.p:b-a.d.length};f.transformCursor=function(b,a,c){var d,e,h;for(e=0,h=a.length;e<h;e++)d=a[e],b=z(b,d,c);return b};f._tc=E=function(b,a,c,d){var e,h;s([a]);s([c]);if(a.i!=q)k(b,{i:a.i,p:z(a.p,c,d==="right")});else if(c.i!=q)d=a.d,a.p<c.p&&(k(b,{d:d.slice(0,c.p-a.p),p:a.p}),d=d.slice(c.p-a.p)),d!==""&&k(b,{d:d,p:a.p+c.i.length});else if(a.p>=c.p+c.d.length)k(b,
{d:a.d,p:a.p-c.d.length});else if(a.p+a.d.length<=c.p)k(b,a);else if(d={d:"",p:a.p},a.p<c.p&&(d.d=a.d.slice(0,c.p-a.p)),a.p+a.d.length>c.p+c.d.length&&(d.d+=a.d.slice(c.p+c.d.length-a.p)),h=Math.max(a.p,c.p),e=Math.min(a.p+a.d.length,c.p+c.d.length),a=a.d.slice(h-a.p,e-a.p),e=c.d.slice(h-c.p,e-c.p),a!==e&&g(Error("Delete ops delete different text in the same region of the document")),d.d!=="")d.p=z(d.p,c),k(b,d);return b};H=function(b){return b.i!=q?{d:b.i,p:b.p}:{i:b.d,p:b.p}};f.F=f.invert=function(b){var a,
c,d,e;d=b.slice().reverse();e=[];for(a=0,c=d.length;a<c;a++)b=d[a],e.push(H(b));return e};typeof!0!=="undefined"?(l.types||(l.types={}),B(f,E,s,k),l.types.text=f):(module.n=f,require("./helpers").u(f,E,s,k));typeof!0==="undefined"&&(f=require("./text"));f.api={provides:{text:!0},getLength:function(){return this.g.length},getText:function(){return this.g},insert:function(b,a,c){a==q&&(a=0);b=[{p:a,i:b}];this.s(b,c);return b},del:function(b,a,c){b=[{p:a,d:this.g.slice(a,a+b)}];this.s(b,c);return b},
_register:function(){return this.f("remoteop",function(b){var a,c,d,e;e=[];for(c=0,d=b.length;c<d;c++)a=b[c],e.push(a.i!==n?this.a("insert",a.i,a.p):this.a("delete",a.d,a.p));return e})}};typeof!0!=="undefined"?(v||(v=l.types),window.io||g(Error("Must load socket.io before this library")),C=window.io):(v=require("../types"),C=require("socket.io-client"),o=require("./microevent"));w=function(b,a,c,d,e){var h,f,l,m,i,k,o;this.name=a;this.version=c;this.type=d;this.type.compose==q&&g(Error("Handling types without compose() defined is not currently implemented"));
k=j(function(a){return this.snapshot=this.g=a},this);k(e);f=q;h=[];i=q;m=[];o=j(function(){if(f===q&&i!==q)return f=i,h=m,i=q,m=[],b.send({doc:this.name,op:f,v:this.version},j(function(a,b){var c,e,j;if(b){d.invert?(c=this.type.invert(f),i&&(c=this.type.transform(c,i,"left")),k(this.type.apply(this.g,c))):g(Error("Op apply failed ("+a.error+") and the OT type does not define an invert function."));for(e=0,j=h.length;e<j;e++)c=h[e],c(q,b)}else{a.v!==this.version&&g(Error("Invalid version from server"));
this.version++;for(e=0,j=h.length;e<j;e++)c=h[e],c(f,q)}f=q;return o()},this))},this);this.t=function(a){var b,c,d;if(!(a.v<this.version))return a.doc!==this.name&&g(Error("Expected docName "+this.name+" but got "+a.doc)),a.v!==this.version&&g(Error("Expected version "+this.version+" but got "+a.v)),a=a.op,c=this.type.transformX||j(function(a,b){var c,d;c=this.type.transform(a,b,"left");d=this.type.transform(b,a,"right");return[c,d]},this),f!==q&&(b=c(f,a),f=b[0],a=b[1]),i!==q&&(d=c(i,a),i=d[0],a=
d[1]),b=this.g,k(this.type.apply(b,a)),this.version++,this.a("remoteop",a,b),this.a("change",a,b)};this.submitOp=this.s=function(a,b){this.type.normalize!=q&&(a=this.type.normalize(a));k(this.type.apply(this.g,a));i=i!==q?this.type.compose(i,a):a;b&&m.push(b);this.a("change",a);return setTimeout(o,0)};this.flush=function(){return o()};this.close=this.close=function(a){return b.send({doc:this.name,open:!1},j(function(){a&&a();this.a("closed")},this))};if(this.type.api){c=this.type.api;for(l in c)a=
c[l],this[l]=a;typeof this._register==="function"&&this._register()}else this.G=this.provides={};return this};o.q(w);u=function(){function b(a){this.m=j(this.m,this);this.h=j(this.h,this);this.l=j(this.l,this);this.e={};this.k=0;this.j={};this.b=C.connect(a,{"force new connection":!0});this.b.on("connect",this.h);this.b.on("disconnect",this.l);this.b.on("message",this.m);this.b.on("connect_failed",j(function(a){var b,e,h,f,j,k,i;a==="unauthorized"&&(a="forbidden");this.b=q;this.a("connect failed",
a);k=this.j;i=[];for(h in k)f=k[h],i.push(function(){var h;h=[];for(j in f)e=f[j],h.push(function(){var h,f,i;i=[];for(h=0,f=e.length;h<f;h++)b=e[h],i.push(b(q,a));return i}());return h}());return i},this));this.b.socket.connected&&setTimeout(j(function(){return this.h()},this),0)}b.prototype.l=function(){return this.a("disconnect")};b.prototype.h=function(){return this.a("connect")};b.prototype.send=function(a,b){var d,e,h;this.b===q&&g(Error("Cannot send messages to a closed connection"));e=a.doc;
e===this.A?delete a.doc:this.A=e;this.b.json.send(a);if(b)return d=a.open===!0?"open":a.open===!1?"close":a.create?"create":a.snapshot===q?"snapshot":a.op?"op response":n,e=(h=this.j)[e]||(h[e]={}),d=e[d]||(e[d]=[]),d.push(b)};b.prototype.m=function(a){var b,d,e,h,f,j;e=a.doc;e!==n?this.z=e:a.doc=e=this.z;this.a("message",a);h=a.open===!0||a.open===!1&&a.error?"open":a.open===!1?"close":a.snapshot!==n?"snapshot":a.create?"create":a.op?"op":a.v!==n?"op response":n;if(d=(b=this.j[e])!=q?b[h]:n){delete this.j[e][h];
for(f=0,j=d.length;f<j;f++)b=d[f],b(a,a.error)}if(h==="op"&&(d=this.e[e]))return d.t(a)};b.prototype.o=function(a){var b,d;d=a.doc;this.e[d]&&g(Error("Doc "+d+" already open"));b=a.type;typeof b==="string"&&(b=v[b]);b=new w(this,d,a.v,b,a.snapshot);b.created=!!a.create;this.e[d]=b;this.k++;b.f("closed",j(function(){delete this.e[d];return this.k--},this));return b};b.prototype.openExisting=function(a,b){if(this.b===q)b(q,"connection closed");else return this.e[a]!=q?this.e[a]:this.send({doc:a,open:!0,
snapshot:q},j(function(a,e){return e?b(q,e):b(this.o(a))},this))};b.prototype.open=function(a,b,d){if(this.b===q)d(q,"connection closed");else if(typeof b==="function"&&(d=b,b="text"),d||(d=function(){}),typeof b==="string"&&(b=v[b]),b||g(Error("OT code for document type missing")),a!=q&&this.e[a]!=q)a=this.e[a],a.type===b?d(a):d(a,"Type mismatch");else return this.send({doc:a,open:!0,create:!0,snapshot:q,type:b.name},j(function(a,f){return f?d(q,f):(a.snapshot===n&&(a.snapshot=b.create()),a.type=
b,d(this.o(a)))},this))};b.prototype.create=function(a,b){return x(q,a,b)};b.prototype.disconnect=function(){if(this.b)return this.a("disconnected"),this.b.disconnect(),this.b=q};return b}();o.q(u);t={};G=function(b){var a;if(typeof!0!=="undefined")a=window.location,b==q&&(b=""+a.protocol+"//"+a.hostname+"/sjs");t[b]||(a=new u(b),a.f("disconnected",function(){return delete t[b]}),a.f("connect failed",function(){return delete t[b]}),t[b]=a);return t[b]};x=function(b,a,c,d){var e;typeof c==="function"&&
(d=c,c=q);e=G(c);e.open(b,a,function(a,b){return a===q?(e.k===0&&e.disconnect(),d(q,b)):(a.f("closed",function(){return setTimeout(function(){if(e.k===0)return e.disconnect()},0)}),d(a))});return e.f("connect failed")};typeof!0!=="undefined"?(l.Connection=u,l.Doc=w,l.open=x,window.sharejs=l):(l.B=u,l.open=x)}).call(this);})();