/*
 ShareJS v0.2
 http://sharejs.org

 Copyright 2011 Joseph Gentle

 BSD licensed:
 https://github.com/josephg/ShareJS/raw/master/LICENSE
*/
function f(i){throw i;}var k=void 0,r=null;
(function(){function i(b,a){return function(){return b.apply(a,arguments)}}var n,p,q,x,l,z,o,A,s,m,B,C,D,t,h,y,E,u,v,w,F=Array.prototype.slice;m={};q=function(){function b(){}b.prototype.b=function(a,c){var b;this.e||(this.e={});(b=this.e)[a]||(b[a]=[]);this.e[a].push(c);return this};b.prototype.m=function(a,c){var b,e;this.e||(this.e={});b=(e=this.e[a])!=r?e.indexOf(c):k;b!=r&&b>=0&&this.e[a].splice(b,1);return this};b.prototype.h=function(){var a,c,b,e,g;c=arguments[0];a=2<=arguments.length?F.call(arguments,
1):[];if(!((b=this.e)!=r&&b[c]))return this;g=this.e[c];b=0;for(e=g.length;b<e;b++)c=g[b],c.apply(this,a);return this};return b}();q.D=function(b){b=b.prototype||b;b.b=b.on=q.prototype.b;b.m=b.removeListener=q.prototype.m;b.h=q.prototype.h};if(typeof module!="undefined"&&module!==r&&module.H)module.H=q;h={name:"text",Q:function(){return""}};t=function(b,a,c){return b.slice(0,a)+c+b.slice(a)};z=function(b){typeof b.p!=="number"&&f(Error("component missing position field"));typeof b.i==="string"^typeof b.d===
"string"||f(Error("component needs an i or d field"));b.p>=0||f(Error("position cannot be negative"))};o=function(b){var a,c,d;c=0;for(d=b.length;c<d;c++)a=b[c],z(a)};h.apply=function(b,a){var c,d,e,g;o(a);e=0;for(g=a.length;e<g;e++)c=a[e],c.i!=r?b=t(b,c.p,c.i):(d=b.slice(c.p,c.p+c.d.length),c.d!==d&&f(Error("Delete component '"+c.d+"' does not match deleted text '"+d+"'")),b=b.slice(0,c.p)+b.slice(c.p+c.d.length));return b};h.N=l=function(b,a){var c,d,e;if(!(a.i===""||a.d===""))return b.length===
0?b.push(a):(c=b[b.length-1],c.i!=r&&a.i!=r&&c.p<=(d=a.p)&&d<=c.p+c.i.length?b[b.length-1]={i:t(c.i,a.p-c.p,a.i),p:c.p}:c.d!=r&&a.d!=r&&a.p<=(e=c.p)&&e<=a.p+a.d.length?b[b.length-1]={d:t(a.d,c.p-a.p,c.d),p:a.p}:b.push(a))};h.A=A=function(b,a){var c,d,e,g;o(b);o(a);d=b.slice();e=0;for(g=a.length;e<g;e++)c=a[e],l(d,c);o(d);return d};h.P=function(b){return A([],b)};h.normalize=function(b){var a,c,d,e;c=[];if(b.i!=r||b.p!=r)b=[b];d=0;for(e=b.length;d<e;d++)a=b[d],a.p!=r||(a.p=0),l(c,a);return c};u=function(b,
a,c){return a.i!=r?a.p<b||a.p===b&&c?b+a.i.length:b:b<=a.p?b:b<=a.p+a.d.length?a.p:b-a.d.length};h.V=function(b,a,c){var d,e,g;e=0;for(g=a.length;e<g;e++)d=a[e],b=u(b,d,c);return b};y=function(b,a,c,d){var e,g;o([a]);o([c]);if(a.i!=r)l(b,{i:a.i,p:u(a.p,c,d==="server")});else if(c.i!=r)d=a.d,a.p<c.p&&(l(b,{d:d.slice(0,c.p-a.p),p:a.p}),d=d.slice(c.p-a.p)),d!==""&&l(b,{d:d,p:a.p+c.i.length});else if(a.p>=c.p+c.d.length)l(b,{d:a.d,p:a.p-c.d.length});else if(a.p+a.d.length<=c.p)l(b,a);else if(d={d:"",
p:a.p},a.p<c.p&&(d.d=a.d.slice(0,c.p-a.p)),a.p+a.d.length>c.p+c.d.length&&(d.d+=a.d.slice(c.p+c.d.length-a.p)),g=Math.max(a.p,c.p),e=Math.min(a.p+a.d.length,c.p+c.d.length),a=a.d.slice(g-a.p,e-a.p),e=c.d.slice(g-c.p,e-c.p),a!==e&&f(Error("Delete ops delete different text in the same region of the document")),d.d!=="")d.p=u(d.p,c),l(b,d)};E=function(b,a,c,d){y(c,b,a,"server");y(d,a,b,"client")};h.L=v=function(b,a){var c,d,e,g,j,i,h,m,n;o(b);o(a);e=[];i=0;for(m=a.length;i<m;i++){d=a[i];g=[];for(c=0;c<
b.length;)if(j=[],E(b[c],d,g,j),c++,j.length===1)d=j[0];else{if(j.length===0){h=b.slice(c);d=0;for(j=h.length;d<j;d++)c=h[d],l(g,c)}else{d=v(b.slice(c),j);j=d[0];d=d[1];h=0;for(n=j.length;h<n;h++)c=j[h],l(g,c);j=0;for(h=d.length;j<h;j++)c=d[j],l(e,c)}d=r;break}d!=r&&l(e,d);b=g}return[b,e]};h.transform=function(b,a,c){c==="server"||c==="client"||f(Error("type must be 'server' or 'client'"));c==="server"?(b=v(b,a),b=b[0]):(b=v(a,b),b=b[1]);return b};C=function(b){return b.i!=r?{d:b.i,p:b.p}:{i:b.d,
p:b.p}};h.R=function(b){var a,c,d,e;d=b.slice().reverse();e=[];a=0;for(c=d.length;a<c;a++)b=d[a],e.push(C(b));return e};m.types||(m.types={});m.types.text=h;window.io||f(Error("Must load socket.io before this library"));D=window.io;x=function(){function b(a,c,b){this.u=i(this.u,this);this.k=new D.Socket(a,{port:c,U:b?b+"/socket.io":"socket.io"});this.k.on("connect",this.I);this.k.on("message",this.u);this.k.connect();this.j={};this.C=this.B=r}b.prototype.I=function(){};b.prototype.b=function(a,c,
b){var e;(e=this.j)[a]||(e[a]={});this.j[a][c]!=r&&f(Error("Callback already exists for "+a+", "+c));return this.j[a][c]=b};b.prototype.m=function(a,c){var b;return(b=this.j[a])!=r?delete b[c]:k};b.prototype.u=function(a){var c;a.doc!=r?this.B=a.doc:a.doc=this.B;c=i(function(c,b){var g,j;g=(j=this.j[a.doc])!=r?j[c]:k;if(g!=r)return b&&(this.j[a.doc][c]=r),g(a)},this);if(a.snapshot!==k)return c("snapshot",!0);else if(a.follow!=r)return a.follow?c("follow",!0):c("unfollow",!0);else if(a.v!==k)return a.op!=
r?c("op",!1):c("localop",!0)};b.prototype.send=function(a){a.doc===this.C?delete a.doc:this.C=a.doc;return this.k.send(a)};b.prototype.q=function(a,c,b){var e;e={doc:a,follow:!0};c!=r&&(e.v=c);this.send(e);return this.b(a,"follow",b)};b.prototype.get=function(a,c){this.send({doc:a,snapshot:r});return this.b(a,"snapshot",c)};b.prototype.submit=function(a,c,b,e){this.send({doc:a,v:b,op:c});return this.b(a,"localop",e)};b.prototype.z=function(a,c){this.send({doc:a,follow:!1});return this.b(a,"unfollow",
c)};b.prototype.o=function(){this.k.disconnect();return this.k=r};return b}();m.M=x;w||(w=m.types);p=function(){function b(a,c,b,e,g){this.a=a;this.name=c;this.version=b;this.type=e;this.l=i(this.l,this);this.n=i(this.n,this);this.type.A==r&&f(Error("Handling types without compose() defined is not currently implemented"));this.snapshot=g;this.c=r;this.r=[];this.f=r;this.w=[];this.F={};this.S=[];this.G=!1;this.q()}b.prototype.q=function(a){this.a.b(this.name,"op",this.l);return this.a.q(this.name,
this.version,i(function(c){c.v!==this.version&&f(Error("Expected version "+this.version+" but got "+c.v));if(a!=r)return a()},this))};b.prototype.z=function(a){this.a.m(this.name,"op",this.l);return this.a.z(this.name,a)};b.prototype.n=function(){if(this.c===r&&this.f!==r)return this.c=this.f,this.r=this.w,this.f=r,this.w=[],this.a.submit(this.name,this.c,this.version,i(function(a){var c,b,e,g;if(a.v===r){g=this.r;b=0;for(e=g.length;b<e;b++)c=g[b],c(r);this.c=r;f(Error(a.error))}a.v!==this.version&&
f(Error("Invalid version from server"));this.F[this.version]=this.c;this.version++;e=this.r;a=0;for(b=e.length;a<b;a++)c=e[a],c(this.c,r);this.c=r;return this.n()},this))};b.prototype.l=function(a){var c,b;if(!(a.v<this.version)){a.doc!==this.name&&f(Error("Expected docName "+this.name+" but got "+a.doc));a.v!==this.version&&f(Error("Expected version "+this.version+" but got "+a.v));a=a.op;this.F[this.version]=a;c=this.type.L||i(function(a,c){var b,d;d=this.type.transform(a,c,"server");b=this.type.transform(c,
a,"client");return[d,b]},this);if(this.c!==r)b=c(a,this.c),a=b[0],this.c=b[1];if(this.f!==r)c=c(a,this.f),a=c[0],this.f=c[1];this.snapshot=this.type.apply(this.snapshot,a);this.version++;this.h("remoteop",a);return this.h("change",a)}};b.prototype.K=function(a,c,b){var e;if(c==r)c=this.version;if(typeof c==="function")b=c,c=this.version;if(((e=this.type)!=r?e.normalize:k)!=r)a=this.type.normalize(a);for(;c<this.version;)(e=this.T[c])||f(Error("Op version too old")),a=this.type.transform(a,e,"client"),
c++;this.snapshot=this.type.apply(this.snapshot,a);this.f=this.f!==r?this.type.A(this.f,a):a;b&&this.w.push(b);this.h("change",a);return setTimeout(this.n,0)};b.prototype.close=function(a){return this.z(i(function(){a&&a();this.h("closed")},this))};return b}();q.D(p);p.prototype.submitOp=p.prototype.K;p.prototype.close=p.prototype.close;n=function(){function b(a,b,d){this.a=new x(a,b,d);this.g={};this.t=0}b.prototype.s=function(a,b,d,e){this.g[a]&&f(Error("Document "+a+" already followed"));b=new p(this.a,
a,b,d,e);this.g[a]=b;this.t++;b.b("closed",i(function(){delete this.g[a];return this.t--},this));return b};b.prototype.J=function(a,b){if(this.g[a]!=r)return this.g[a];return this.a.get(a,i(function(a){var e;return a.snapshot===r?b(r):(e=w[a.type],b(this.s(a.doc,a.v,e,a.snapshot)))},this))};b.prototype.open=function(a,b,d){var e;typeof b==="function"&&(d=b,b="text");d||(d=function(){});typeof b==="string"&&(b=w[b]);if(this.g[a]!=r)e=this.g[a],e.type===b?d(e):d(e,"Document already exists with type "+
e.type.name);else return this.a.get(a,i(function(g){return g.snapshot===r?this.a.submit(a,{type:b.name},0,i(function(g){return g.v!=r?(e=this.s(a,1,b,""),e.G=!0,d(e)):g.v===r&&g.error==="Type already set"?this.open(a,b,d):d(r,g.error)},this)):g.type===b.name?d(this.s(a,g.v,b,g.snapshot)):d(r,"Document already exists with type "+g.type)},this))};b.prototype.o=function(){if(this.a!=r)return this.h("disconnected"),this.a.o(),this.a=r};return b}();n.prototype.openExisting=n.prototype.J;n.prototype.open=
n.prototype.open;q.D(n);s={};B=function(b,a,c){var d;b!=r||(b=window.location.hostname);a!=r||(a=window.location.port);d=b;a!=r&&(d+=":"+a);s[d]||(b=new n(b,a,c),b.b("disconnected",function(){return delete s[d]}),s[d]=b);return s[d]};m.Connection=n;m.Document=p;m.open=function(b,a,c,d){var e;typeof c==="function"&&(d=c,c=r);c!=r||(c={});e=B(c.host,c.port,c.O);return e.open(b,a,function(a){a.b("closed",function(){return setTimeout(function(){if(e.t===0)return e.o()},0)});return d(a)})};window.sharejs=
m}).call(this);